### ISSUE TITLE
Enhance Helm chart to use Secrets created by External Secrets Operator

### ISSUE THREAD

**Issue by dwinchell** [ploigos/infra-ops#37]
Success Criteria:
* We can run our fork of the openshift-actions-runner-chart without supplying any secrets at the command line
    * https://github.com/ploigos/openshift-actions-runner-chart
* The secrets that the chart uses come from Vault, via the Secret that the External Secrets Operator creates

**Comment by dwinchell** [comment]
@aarongreen85 the idea was #34 / #36 make Helm create ExternalSecrets. This issue is about using them to do something useful (i.e. consuming the info in the Secrets). It's possible that no additional work is required for that latter part, or that it would be easier to roll that scope into the other tickets. I'm fine however you want to divide the work.

**Comment by gfulton-redhat** [comment]
Closed by #34 and #36
